name: 🐛 Report a Bug
description: Report a problem with Celestial.
title: "[Bug]: "
labels: ["Bug: Unconfirmed"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Not sure if this is a bug with  Celestial? Feel free to ask !

        When completing the report, please ensure all fields are filled with the correct details requested. Failure to do so will result in your issue being closed.
  - type: input
    id:  celestial-version-info
    attributes:
      label: ' Celestial Version'
      description: We need to know if this is the Stable version or Dev Version
    validations:
      required: true
  - type: input
    id: server-logs
    attributes:
      label: Console logs
      description: >
        Include full startup log and console error (if any). upload all relevant logs to either https://paste.gg
        or https://gist.github.com, save and the paste the link in this box.
    validations:
      required: true
  - type: textarea
    id: server-info
    attributes:
      label: Server Version
      description: OS and Java version
      placeholder: server version info
      render: shell
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Describe in detail what the bug is about. Include the expected behaviour and actual behaviour.
      placeholder: "Example: When running `/stats` it cause the bot to crash..."
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Provide detailed intructions to trigger the bug.
      placeholder: |
        Example:
          1. Start a instance with the latest version of  Celestial .
          2. Run `/stats` command.
          3. Bot shuts down with an error.
          ...
    validations:
      required: true
  - type: checkboxes
    id: agreements
    attributes:
      label: Agreements
      description: Ensure you have done the following being submitting this issue.
      options:
        - label: I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
          required: true
        - label: >
            I was able to reproduce my issue on a freshly setup and up-to-date server with the latest
            version of Celestial with no other plugins and with no kinds of other server or client mods.
          required: true