name: Trigger Jenkins Job

on:
  push:
    branches:
      - main
      - developer

jobs:
  trigger-jenkins-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Jenkins Job
        run: |
          curl -X POST "https://ci.bunni.me/buildByToken/buildWithParameters?job=Celestial%20Bot" \
          --user ${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_TOKEN }} \
          --data-urlencode json='{"parameter": [{"name":"param_name", "value":"param_value"}]}'